### ISSUE TITLE
Remote Connections may not work 

### ISSUE THREAD

**Issue by fashaikh** [Azure/Azure-Websites-Migration-Tool#25]
```
*** Unable to connect to server ***

26/11/2018 7:50:51 PM : System.Net.Sockets.SocketException (0x80004005): No such host is known
at System.Net.Dns.InternalGetHostByAddress(IPAddress address, Boolean includeIPv6)
at System.Net.Dns.GetHostEntry(String hostNameOrAddress)
at AzureAppServiceMigrationAssistant.Helpers.Helper.IsComputerReachable(String computername)

```

**Comment by fashaikh** [comment]
Project is in maintenance mode
