### ISSUE TITLE
Installation Issues

### ISSUE THREAD

**Issue by kvaes** [Azure/Azure-Websites-Migration-Tool#8]
When using the following link to install ; https://www.movemetothecloud.net/WindowsMigration 

* Install tool fails due to an untrusted source
* Offline install fails due to a dependent package not being available.

System.Net.WebException: Url 'https://developer.microsoft.com/en-us/web/webpi/5.0/webproductlist.xml' returned HTTP status code: 404
   at Microsoft.Web.PlatformInstaller.ManagedWinInet.OpenUrlAndFollowRedirects(Uri& uri, IntPtr& hInetFile)
   at Microsoft.Web.PlatformInstaller.ManagedWinInet.DownloadFile(Uri uri, String fileName, String& contentDispositionFileName)
   at Microsoft.Web.PlatformInstaller.ProductManager.DownloadFile(Uri url, String cacheFileLocation, DateTime productFileLastModified)
   at Microsoft.Web.PlatformInstaller.ProductManager.Load(Uri productFileUrl, Boolean filterByArchitectureAndOS, Boolean loadEnclosures, Boolean useCachedVersion, String cacheDirectory, Architecture architecture, Int32 osType)
   at CompatCheckAndMigrate.Helpers.WebPlatformInstallHelper.SetupInstall(String[] productList)
   at CompatCheckAndMigrate.Helpers.Helper.SetupInstall()

**Comment by fashaikh** [comment]
The clickonce application has been updated. You may need to uninstall and re-install from the website. 

The offline package from here  https://movemetothecloud.net/WindowsMigration now  contains additional dependencies.
